baseurl = "http://r21nomi.github.io/processing_work"
languageCode = "en-us"
title = "Processing Work"
theme = "custom"

[params]
    description = "Experimental works for processing"
    author = "Ryota Niinomi"
